# SPDX-FileCopyrightText: 2022-2026 TII (SSRC) and the Ghaf contributors
# SPDX-License-Identifier: Apache-2.0

version = 1
SPDX-PackageName = "ghaf"
SPDX-PackageSupplier = "Technology Innovation Institute <https://tii.ae>"
SPDX-PackageDownloadLocation = "https://github.com/tiiuae/ghaf"

[[annotations]]
SPDX-License-Identifier = "Apache-2.0"
SPDX-FileCopyrightText = "2022-2026 TII (SSRC) and the Ghaf contributors"
precedence = "closest"
path = [
  ".github/dependabot.yml",
  ".github/copilot-instructions.md",
  ".github/workflows/codeql.yml",
  ".github/workflows/dependency-review.yml",
  ".pre-commit-config.yaml",
  "flake.lock",
  ".version",
  "assets/**/*.png",
  "assets/**/*.svg",
  "lib/builders/README.md",
  "modules/development/audio_test/test_file1.mp3",
  "modules/hardware/x86_64-generic/kernel/host/configs/ghaf_host_hardened_baseline-x86",
  "modules/hardware/x86_64-generic/kernel/guest/configs/ghaf_guest_hardened_baseline-x86",
  "modules/reference/hardware/jetpack/ghaf_host_hardened_baseline-jetson-orin",
  "modules/microvm/sysvms/idsvm/mitmproxy/mitmproxy-ca/*",
  "modules/reference/hardware/jetpack/0001-ARM-SMMU-drivers-return-always-true-for-IOMMU_CAP_CA.patch",
  "packages/pkgs-by-name/ghaf-intro/**/*.png",
  "overlays/custom-packages/cosmic/cosmic-comp/0001-Add-security-context-indicator.patch",
  "overlays/custom-packages/cosmic/cosmic-comp/0001-Disable-VRR-by-default.patch",
  "overlays/custom-packages/cosmic/cosmic-initial-setup/0001-Preselect-Ghaf-themes.patch",
  "overlays/custom-packages/cosmic/cosmic-greeter/0001-Replace-fallback-background-with-Ghaf-default.patch",
  "overlays/custom-packages/cosmic/cosmic-applets/*.patch",
  "overlays/custom-packages/system76-scheduler/0001-fix-add-missing-loop-in-process-scheduler-refresh-ta.patch",
  "overlays/custom-packages/cosmic/cosmic-greeter/0001-Fix-softlock.patch",
  "overlays/custom-packages/cosmic/cosmic-greeter/0002-fix-username-handle-empty-usernames.patch",
  "modules/secureboot/keys/*",
  "modules/hardware/passthrough/pci-acs-override/0001-pci-add-pcie_acs_override-for-pci-passthrough.patch"
]

[[annotations]]
SPDX-License-Identifier = "CC-BY-SA-4.0"
SPDX-FileCopyrightText = "2022-2024 TII (SSRC) and the Ghaf contributors"
precedence = "closest"
path = [
  "docs/**/*.svg",
  "docs/**/*.png",
  "docs/**/*.md",
  "docs/**/*.mdx",
  "docs/**/*.astro",
  "docs/package-lock.json",
  "docs/package.json",
  "docs/public/CNAME",
]

[[annotations]]
# See https://github.com/qemu/qemu/blob/master/LICENSE
# Our changes affects the GPL-2.0+ parts only.
SPDX-License-Identifier = "GPL-2.0-or-later"
SPDX-FileCopyrightText = [
  "Fabrice Bellard and the QEMU team",
  "Copyright (c) 2021-2022 Canokeys.org <contact@canokeys.org>",
  "Written by Hongren (Zenithal) Zheng <i@zenithal.me>",
  "Copyright (c) 2019 Janus Technologies, Inc. (http://janustech.com)",
  "Copyright (C) 2008-2010  Kevin O'Connor <kevin@koconnor.net>",
  "Copyright (C) 2006 Fabrice Bellard",
  "Copyright (C) 2013 Red Hat Inc"
]
path = [
  "overlays/custom-packages/qemu/*.patch",
  "modules/reference/hardware/jetpack/nvidia-jetson-orin/virtualization/host/bpmp-virt-host/overlays/qemu/patches/0001-qemu-v8.1.3_bpmp-virt.patch"
]

[[annotations]]
SPDX-License-Identifier = "GPL-2.0-only"
SPDX-FileCopyrightText = "labwc contributors"
path = "overlays/custom-packages/labwc/*.patch"

[[annotations]]
SPDX-License-Identifier = "LGPL-2.1-or-later"
SPDX-FileCopyrightText = "systemd contributors"
path = [
	"modules/common/systemd/systemd-boot-double-dtb-buffer-size.patch",
	"modules/common/systemd/systemd-localed-locale-archive.patch",
	"modules/common/systemd/systemd-re-enable-locale-setting.patch",
]

[[annotations]]
SPDX-License-Identifier = "MIT"
SPDX-FileCopyrightText = "Copyright Â© 2019 Manuel Stoeckl"
path = "overlays/custom-packages/waypipe/waypipe-window-borders.patch"

[[annotations]]
SPDX-License-Identifier = "Apache-2.0"
SPDX-FileCopyrightText = "Copyright 2023 The Matrix.org Foundation C.I.C."
path = "packages/pkgs-by-name/element-web/*.patch"

[[annotations]]
SPDX-License-Identifier = "Apache-2.0"
SPDX-FileCopyrightText = [
  "Copyright 2016 Aviral Dasgupta",
  "Copyright 2016 OpenMarket Ltd",
  "Copyright 2017, 2019 Michael Telatynski <7t3chguy@gmail.com>",
  "Copyright 2018 - 2021 New Vector Ltd"
]
path = "overlays/custom-packages/element-desktop/element-main.patch"

[[annotations]]
SPDX-License-Identifier = "GPL-2.0-only"
SPDX-FileCopyrightText = [
  "Copyright (C) 2013 - Virtual Open Systems",
  "Copyright (c) 2016, NVIDIA CORPORATION.  All rights reserved.",
  "Copyright (c) 2018, NVIDIA CORPORATION.",
  "Copyright (C) 2006 Qumranet, Inc.",
  "Copyright 2010 Red Hat, Inc. and/or its affiliates.",
  "2022-2024 TII (SSRC) and the Ghaf contributors"
]
path = [
  "modules/reference/hardware/jetpack/nvidia-jetson-orin/virtualization/common/bpmp-virt-common/patches/*.patch",
  "modules/reference/hardware/jetpack/nvidia-jetson-orin/virtualization/host/bpmp-virt-host/patches/*.patch",
  "modules/reference/hardware/jetpack/*.patch",
  "modules/reference/hardware/jetpack/nvidia-jetson-orin/virtualization/passthrough/uarti-net-vm/patches/net_vm_dtb_with_uarti.patch",
  "modules/hardware/x86_64-generic/kernel/pkvm/0001-pkvm-enable-pkvm-on-intel-x86-6.1-lts.patch",
  "modules/microvm/sysvms/0001-x86-gpu-Don-t-reserve-stolen-memory-for-GPU-passthro.patch",
  "modules/reference/hardware/jetpack/nvidia-jetson-orin/virtualization/passthrough/uarti-net-vm/tegra234-netvm.dts"
]

[[annotations]]
SPDX-License-Identifier = "BSD-2-Clause-Patent"
SPDX-FileCopyrightText = "Copyright (c) 2021-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved."
path = "modules/reference/hardware/jetpack/nvidia-jetson-orin/edk2-nvidia-always-reset-display.patch"

[[annotations]]
SPDX-License-Identifier = "LicenseRef-NvidiaProprietary"
SPDX-FileCopyrightText = "Copyright (c) 2023-2024, NVIDIA CORPORATION & AFFILIATES. All rights reserved."
path = [
  "modules/reference/hardware/jetpack/nvidia-jetson-orin/tegra2-mb2-bct-scr.patch"
]

[[annotations]]
SPDX-License-Identifier = "MIT"
SPDX-FileCopyrightText = "Copyright 2019-2021 Microchip Corporation."
path = [
  "packages/hart-software-services/0001-Workaround-for-a-compilation-issue.patch"
]

[[annotations]]
SPDX-License-Identifier = "BSD-2-Clause"
SPDX-FileCopyrightText = "Copyright (c) 2017-2020, Linaro Limited"
path = [
  "targets/nvidia-jetson-orin/0001-ta-pkcs11-Build-time-option-for-controlling-pin-lock.patch",
  "targets/nvidia-jetson-orin/0001-Remove-nvidia-display-config.patch"
]

[[annotations]]
SPDX-License-Identifier = "GPL-3.0-only"
SPDX-FileCopyrightText = "Copyright (C) 2007 Free Software Foundation, Inc."
path = [
  "overlays/custom-packages/gtklock/*.patch"
]

[[annotations]]
SPDX-License-Identifier = "MIT"
SPDX-FileCopyrightText = "igt-gpu-tools contributors"
path = "overlays/custom-packages/intel-gpu-tools/feat-dynamically-detect-iGPU-PCI-address-at-runtime.patch"
