# SPDX-FileCopyrightText: 2022-2026 TII (SSRC) and the Ghaf contributors
# SPDX-License-Identifier: Apache-2.0
com.system76.CosmicAppletTime:
  first_day_of_week: 0
  military_time: false,
  show_seconds: false,
  show_date_in_top_panel: true,
  show_weekday: false,

com.system76.CosmicAppList:
  favorites: |
    [
      "com.system76.CosmicFiles",
      "com.system76.CosmicTerm",
      "com.system76.CosmicSettings",
    ]
  filter_top_levels: None
  enable_drag_source: true

com.system76.CosmicFiles:
  favorites: |
    [
      Home,
      Path("/Shares"),
    ]

com.system76.CosmicBackground:
  all: |
    (
        output: "all",
        source: Path("/run/current-system/sw/share/backgrounds/ghaf/"),
        filter_by_theme: true,
        rotation_frequency: 3600,
        filter_method: Lanczos,
        scaling_mode: Zoom,
        sampling_method: Alphanumeric,
    )
  backgrounds: [All]
  same-on-all: true

com.system76.CosmicComp:
  autotile_behavior: PerWorkspace
  input_default: |
    (
        state: Enabled,
        scroll_config: Some((
            method: None,
            natural_scroll: Some(false),
            scroll_button: None,
            scroll_factor: None,
        )),
    )
  input_touchpad: |
    (
        state: Enabled,
        click_method: Some(Clickfinger),
        scroll_config: Some((
            method: Some(TwoFinger),
            natural_scroll: Some(true),
            scroll_button: None,
            scroll_factor: None,
        )),
        tap_config: Some((
            enabled: true,
            button_map: Some(LeftRightMiddle),
            drag: true,
            drag_lock: false,
        )),
    )
  workspaces: |
    (
        workspace_mode: OutputBound,
        workspace_layout: Horizontal,
    )

com.system76.CosmicIdle:
  screen_off_time: None
  suspend_on_ac_time: None
  suspend_on_battery_time: None

com.system76.CosmicPanel:
  entries: |
    [
        "Panel",
        "Dock",
    ]

com.system76.CosmicPanel-bottom-panel:
  entries: |
    [
        "Panel",
    ]

com.system76.CosmicPanel.Dock:
  anchor: Bottom
  anchor_gap: true
  autohide: |
    Some((
        wait_time: 1000,
        transition_time: 200,
        handle_size: 4,
    ))
  autohover_delay_ms: Some(500)
  background: ThemeDefault
  border_radius: 8
  exclusive_zone: false
  expand_to_edges: false
  keyboard_interactivity: OnDemand
  layer: Overlay
  margin: 4
  name: "Dock"
  opacity: 0.75
  output: All
  padding: 0
  plugins_center: |
    Some([
        "com.system76.CosmicAppList",
    ])
  plugins_wings: |
    Some(([
        "com.system76.CosmicPanelAppButton",
    ], [
        "com.system76.CosmicAppletMinimize",
    ]))
  size: L
  size_center: None
  size_wings: None
  spacing: 4

com.system76.CosmicPanel.Panel:
  anchor: Top
  anchor_gap: false
  autohide: None
  autohover_delay_ms: Some(500)
  background: ThemeDefault
  border_radius: 0
  exclusive_zone: true
  expand_to_edges: true
  keyboard_interactivity: OnDemand
  layer: Top
  margin: 0
  name: "Panel"
  opacity: 0.5
  output: All
  padding: 0
  plugins_center: |
    Some([
        "com.system76.CosmicAppletTime",
        "com.system76.CosmicAppletNotifications",
    ])
  plugins_wings: |
    Some(([
        "com.system76.CosmicPanelAppButton",
        "com.system76.CosmicPanelWorkspacesButton",
    ], [
        "com.system76.CosmicAppletInputSources",
        "com.system76.CosmicAppletStatusArea",
        "com.system76.CosmicAppletTiling",
        "com.system76.CosmicAppletNetwork",
        "com.system76.CosmicAppletAudio",
        "com.system76.CosmicAppletBattery",
        "com.system76.CosmicAppletPower",
    ]))
  size: XS
  spacing: 2

com.system76.CosmicPanel.Panel-bottom-panel:
  anchor: Bottom
  anchor_gap: false
  autohide: None
  autohover_delay_ms: Some(500)
  background: ThemeDefault
  border_radius: 0
  exclusive_zone: false
  expand_to_edges: true
  keyboard_interactivity: OnDemand
  layer: Top
  margin: 0
  name: "Panel"
  opacity: 0.75
  output: All
  padding: 0
  plugins_center: Some([])
  plugins_wings: |
    Some(([
        "com.system76.CosmicPanelLauncherButton",
        "com.system76.CosmicPanelWorkspacesButton",
        "com.system76.CosmicPanelAppButton",
        "com.system76.CosmicAppList",
        "com.system76.CosmicAppletMinimize",
    ], [
        "com.system76.CosmicAppletInputSources",
        "com.system76.CosmicAppletStatusArea",
        "com.system76.CosmicAppletA11y",
        "com.system76.CosmicAppletTiling",
        "com.system76.CosmicAppletAudio",
        "com.system76.CosmicAppletBluetooth",
        "com.system76.CosmicAppletNetwork",
        "com.system76.CosmicAppletBattery",
        "com.system76.CosmicAppletNotifications",
        "com.system76.CosmicAppletTime",
        "com.system76.CosmicAppletPower",
    ]))
  size: M
  spacing: 2

com.system76.CosmicSettings.Shortcuts:
  defaults: |
    {
        (modifiers: [Super, Alt], key: "Escape"): Terminate,
        (modifiers: [Super, Shift], key: "Escape"): System(LogOut),
        (modifiers: [Super, Ctrl], key: "Escape"): Debug,
        (modifiers: [Super], key: "Escape"): System(LockScreen),
        (modifiers: [Super], key: "q"): Close,

        (modifiers: [Super], key: "Left"): Focus(Left),
        (modifiers: [Super], key: "Right"): Focus(Right),
        (modifiers: [Super], key: "Up"): Focus(Up),
        (modifiers: [Super], key: "Down"): Focus(Down),
        (modifiers: [Super], key: "h"): Focus(Left),
        (modifiers: [Super], key: "j"): Focus(Down),
        (modifiers: [Super], key: "k"): Focus(Up),
        (modifiers: [Super], key: "l"): Focus(Right),
        (modifiers: [Super], key: "u"): Focus(Out),
        (modifiers: [Super], key: "i"): Focus(In),
        (modifiers: [Super, Shift], key: "Left"): Move(Left),
        (modifiers: [Super, Shift], key: "Right"): Move(Right),
        (modifiers: [Super, Shift], key: "Up"): Move(Up),
        (modifiers: [Super, Shift], key: "Down"): Move(Down),
        (modifiers: [Super, Shift], key: "h"): Move(Left),
        (modifiers: [Super, Shift], key: "j"): Move(Down),
        (modifiers: [Super, Shift], key: "k"): Move(Up),
        (modifiers: [Super, Shift], key: "l"): Move(Right),

        (modifiers: [Super], key: "1"): Workspace(1),
        (modifiers: [Super], key: "2"): Workspace(2),
        (modifiers: [Super], key: "3"): Workspace(3),
        (modifiers: [Super], key: "4"): Workspace(4),
        (modifiers: [Super], key: "5"): Workspace(5),
        (modifiers: [Super], key: "6"): Workspace(6),
        (modifiers: [Super], key: "7"): Workspace(7),
        (modifiers: [Super], key: "8"): Workspace(8),
        (modifiers: [Super], key: "9"): Workspace(9),
        (modifiers: [Super], key: "0"): LastWorkspace,
        (modifiers: [Super, Shift], key: "1"): MoveToWorkspace(1),
        (modifiers: [Super, Shift], key: "2"): MoveToWorkspace(2),
        (modifiers: [Super, Shift], key: "3"): MoveToWorkspace(3),
        (modifiers: [Super, Shift], key: "4"): MoveToWorkspace(4),
        (modifiers: [Super, Shift], key: "5"): MoveToWorkspace(5),
        (modifiers: [Super, Shift], key: "6"): MoveToWorkspace(6),
        (modifiers: [Super, Shift], key: "7"): MoveToWorkspace(7),
        (modifiers: [Super, Shift], key: "8"): MoveToWorkspace(8),
        (modifiers: [Super, Shift], key: "9"): MoveToWorkspace(9),
        (modifiers: [Super, Shift], key: "0"): MoveToLastWorkspace,

        (modifiers: [Super, Ctrl], key: "Left"): PreviousWorkspace,
        (modifiers: [Super, Ctrl], key: "Down"): NextWorkspace,
        (modifiers: [Super, Ctrl], key: "Up"): PreviousWorkspace,
        (modifiers: [Super, Ctrl], key: "Right"): NextWorkspace,
        (modifiers: [Super, Ctrl], key: "h"): PreviousWorkspace,
        (modifiers: [Super, Ctrl], key: "j"): NextWorkspace,
        (modifiers: [Super, Ctrl], key: "k"): PreviousWorkspace,
        (modifiers: [Super, Ctrl], key: "l"): NextWorkspace,
        (modifiers: [Super, Shift, Ctrl], key: "Left"): MoveToPreviousWorkspace,
        (modifiers: [Super, Shift, Ctrl], key: "Down"): MoveToNextWorkspace,
        (modifiers: [Super, Shift, Ctrl], key: "Up"): MoveToPreviousWorkspace,
        (modifiers: [Super, Shift, Ctrl], key: "Right"): MoveToNextWorkspace,
        (modifiers: [Super, Shift, Ctrl], key: "h"): MoveToPreviousWorkspace,
        (modifiers: [Super, Shift, Ctrl], key: "j"): MoveToNextWorkspace,
        (modifiers: [Super, Shift, Ctrl], key: "k"): MoveToPreviousWorkspace,
        (modifiers: [Super, Shift, Ctrl], key: "l"): MoveToNextWorkspace,

        (modifiers: [Super, Alt], key: "Left"): SwitchOutput(Left),
        (modifiers: [Super, Alt], key: "Down"): SwitchOutput(Down),
        (modifiers: [Super, Alt], key: "Up"): SwitchOutput(Up),
        (modifiers: [Super, Alt], key: "Right"): SwitchOutput(Right),
        (modifiers: [Super, Alt], key: "h"): SwitchOutput(Left),
        (modifiers: [Super, Alt], key: "k"): SwitchOutput(Up),
        (modifiers: [Super, Alt], key: "j"): SwitchOutput(Down),
        (modifiers: [Super, Alt], key: "l"): SwitchOutput(Right),
        (modifiers: [Super, Shift, Alt], key: "Left"): MoveToOutput(Left),
        (modifiers: [Super, Shift, Alt], key: "Down"): MoveToOutput(Down),
        (modifiers: [Super, Shift, Alt], key: "Up"): MoveToOutput(Up),
        (modifiers: [Super, Shift, Alt], key: "Right"): MoveToOutput(Right),
        (modifiers: [Super, Shift, Alt], key: "h"): MoveToOutput(Left),
        (modifiers: [Super, Shift, Alt], key: "k"): MoveToOutput(Up),
        (modifiers: [Super, Shift, Alt], key: "j"): MoveToOutput(Down),
        (modifiers: [Super, Shift, Alt], key: "l"): MoveToOutput(Right),

        (modifiers: [Super], key: "o"): ToggleOrientation,
        (modifiers: [Super], key: "s"): ToggleStacking,
        (modifiers: [Super], key: "y"): ToggleTiling,
        (modifiers: [Super], key: "g"): ToggleWindowFloating,
        (modifiers: [Super], key: "x"): SwapWindow,

        (modifiers: [Super], key: "m"): Maximize,
        (modifiers: [Super], key: "F11"): Fullscreen,
        (modifiers: [Super], key: "r"): Resizing(Outwards),
        (modifiers: [Super, Shift], key: "r"): Resizing(Inwards),

        (modifiers: [Super], key: "equal"): ZoomIn,
        (modifiers: [Super], key: "minus"): ZoomOut,
        (modifiers: [Super], key: "period"): ZoomIn,
        (modifiers: [Super], key: "comma"): ZoomOut,

        (modifiers: [Super], key: "b"): System(WebBrowser),
        (modifiers: [Super], key: "f"): System(HomeFolder),
        (modifiers: [Super], key: "space"): System(InputSourceSwitch),
        (modifiers: [Super], key: "t"): System(Terminal),

        (modifiers: [Super], key: "a"): System(AppLibrary),
        (modifiers: [Super], key: "w"): System(WorkspaceOverview),
        (modifiers: [Super], key: "slash"): System(Launcher),
        (modifiers: [Super]): System(AppLibrary),
        (modifiers: [Alt], key: "Tab"): System(WindowSwitcher),
        (modifiers: [Alt, Shift], key: "Tab"): System(WindowSwitcherPrevious),
        (modifiers: [Super], key: "Tab"): System(WindowSwitcher),
        (modifiers: [Super, Shift], key: "Tab"): System(WindowSwitcherPrevious),

        (modifiers: [], key: "Print"): System(Screenshot),
        (modifiers: [], key: "XF86AudioRaiseVolume"): System(VolumeRaise),
        (modifiers: [], key: "XF86AudioLowerVolume"): System(VolumeLower),
        (modifiers: [], key: "XF86AudioMute"): System(Mute),
        (modifiers: [], key: "XF86AudioMicMute"): System(MuteMic),
        (modifiers: [], key: "XF86MonBrightnessUp"): System(BrightnessUp),
        (modifiers: [], key: "XF86MonBrightnessDown"): System(BrightnessDown),
        (modifiers: [], key: "XF86AudioPlay"): System(PlayPause),
        (modifiers: [], key: "XF86AudioPrev"): System(PlayPrev),
        (modifiers: [], key: "XF86AudioNext"): System(PlayNext),
        (modifiers: [], key: "XF86PowerOff"): System(PowerOff),
        (modifiers: [], key: "XF86TouchpadToggle"): System(TouchpadToggle),
    }
  system_actions: |
    {
        /// Opens the application library
        AppLibrary: "cosmic-app-library",
        /// Decreases screen brightness
        BrightnessDown: "busctl --user call com.system76.CosmicSettingsDaemon /com/system76/CosmicSettingsDaemon com.system76.CosmicSettingsDaemon DecreaseDisplayBrightness",
        /// Increases screen brightness
        BrightnessUp: "busctl --user call com.system76.CosmicSettingsDaemon /com/system76/CosmicSettingsDaemon com.system76.CosmicSettingsDaemon IncreaseDisplayBrightness",
        /// Toggles display mode
        DisplayToggle: "cosmic-osd display",
        /// Switch between input sources
        InputSourceSwitch: "busctl --user call com.system76.CosmicSettingsDaemon /com/system76/CosmicSettingsDaemon com.system76.CosmicSettingsDaemon InputSourceSwitch",
        /// Opens the home folder in a system default file browser
        HomeFolder: "xdg-open ~",
        /// Logs out
        LogOut: "cosmic-osd log-out",
        /// Decreases keyboard brightness
        // KeyboardBrightnessDown,
        /// Increases keyboard brightness
        // KeyboardBrightnessUp,
        /// Opens the launcher
        Launcher: "cosmic-launcher",
        /// Locks the screen
        LockScreen: "loginctl lock-session",
        /// Mutes the active output device
        Mute: "pactl set-sink-mute @DEFAULT_SINK@ toggle",
        /// Mutes the active microphone
        MuteMic: "pactl set-source-mute @DEFAULT_SOURCE@ toggle",
        /// Plays and Pauses audio
        PlayPause: "playerctl play-pause",
        /// Goes to the next track
        PlayNext: "playerctl next",
        /// Goes to the previous track
        PlayPrev: "playerctl previous",
        /// Power off handler
        PowerOff: "cosmic-osd shutdown",
        /// Takes a screenshot
        Screenshot: "cosmic-screenshot",
        /// Suspend the system
        Suspend: "systemctl suspend",
        /// Toggles the screen reader
        ScreenReader: "busctl --user call com.system76.CosmicSettingsDaemon /com/system76/CosmicSettingsDaemon com.system76.CosmicSettingsDaemon ScreenReader",
        /// Opens the system default terminal
        Terminal: "cosmic-term",
        /// Toggles touchpad on/off
        TouchpadToggle: "cosmic-osd touchpad",
        /// Lowers the volume of the active output device (uses wpctl internally)
        VolumeLower: "",
        /// Raises the volume of the active output device (uses wpctl internally)
        VolumeRaise: "",
        /// Opens the system default web browser
        WebBrowser: "xdg-open http://",
        /// Opens the (alt+tab) window switcher
        WindowSwitcher: "cosmic-launcher alt-tab",
        /// Opens the (alt+shift+tab) window switcher
        WindowSwitcherPrevious: "cosmic-launcher shift-alt-tab",
        /// Opens the workspace overview
        WorkspaceOverview: "cosmic-workspaces",
    }

com.system76.CosmicSettings.WindowRules:
  tiling_exception_defaults: |
    [
    	// Any appid title only matching
    	(
    		appid: ".*",
    		titles: [
    			"Discord Updater",
    		]
    	),
    	// Empty appid title only matches
    	(
    		appid: "",
    		titles: [
    			"Steam",
    			"wl-clipboard",
    		]
    	),


    	// Appid matches
    	(appid: "Authy Desktop", titles: [".*"]),
    	(appid: "Com.github.amezin.ddterm", titles: [".*"]),
    	(appid: "Com.github.donadigo.eddy", titles: [".*"]),
    	(appid: "com.system76.CosmicFilesDialog", titles: [".*"]),
    	(appid: "Enpass", titles: ["Enpass Assistant"]),
    	(appid: "Gjs", titles: ["Settings"]),
    	(appid: "Gnome-initial-setup", titles: [".*"]),
    	(appid: "Gnome-terminal", titles: ["Preferences - General"]),
    	(appid: "Guake", titles: [".*"]),
    	(appid: "Io.elementary.sideload", titles: [".*"]),
    	(appid: "KotatogramDesktop", titles: ["Media viewer"]),
    	(appid: "Mozilla VPN", titles: [".*"]),
    	(appid: "update-manager", titles: ["Software Updater"]),
    	(appid: "Solaar", titles: [".*"]),
    	(appid: "Steam", titles: ["^.*?(Guard|Login).*"]),
    	(appid: "TelegramDesktop", titles: ["Media viewer"]),
    	(appid: "Zotero", titles: ["Quick Format Citation"]),
    	(appid: "gjs", titles: [".*"]),
    	(appid: "gnome-screenshot", titles: [".*"]),
    	(appid: "ibus-.*", titles: [".*"]),
    	(appid: "jetbrains-toolbox", titles: [".*"]),
    	(appid: "jetbrains-webstorm", titles: ["Customize WebStorm", "License Activation", "Welcome to WebStorm"]),
    	(appid: "krunner", titles: [".*"]),
    	(appid: "pritunl", titles: [".*"]),
    	(appid: "re.sonny.Junction", titles: [".*"]),
    	(appid: "system76-driver", titles: [".*"]),
    	(appid: "tilda", titles: [".*"]),
    	(appid: "zoom", titles: [".*"]),
    	(appid: "^.*?action=join.*$", titles: [".*"]),

    ]

com.system76.CosmicTerm:
  font_name: "Noto Sans Mono"

com.system76.CosmicTheme.Mode:
  auto_switch: false
  is_dark: true

com.system76.CosmicTk:
  apply_theme_global: true
  show_minimize: true
  show_maximize: true
  icon_theme: "Papirus"
  interface_density: Standard
  header_size: Standard
  interface_font: |
    (
        family: "Inter",
        weight: Normal,
        stretch: Normal,
        style: Normal,
    )
  monospace_font: |
    (
        family: "Noto Sans Mono",
        weight: Normal,
        stretch: Normal,
        style: Normal,
    )
