[book]
title = "Ghaf Framework"
authors = ["Technology Innovation Institute - SSRC"]
description = "Documentation for TII SSRC Secure Technologies."
language = "en"
multilingual = false
src = "src"

[output.html]
default-theme = "light"
git-repository-url = "https://github.com/tiiuae/ghaf"
git-repository-icon = "fa-github"

[preprocessor.footnote]
