# SPDX-FileCopyrightText: 2022-2024 TII (SSRC) and the Ghaf contributors
#
# SPDX-License-Identifier: CC-BY-SA-4.0

[book]
title = "Ghaf Framework"
authors = ["Technology Innovation Institute - SSRC"]
description = "Documentation for TII SSRC Secure Technologies."
language = "en"
multilingual = false
src = "src"

[output.html]
default-theme = "light"
git-repository-url = "https://github.com/tiiuae/ghaf"
git-repository-icon = "fa-github"

[preprocessor.alerts]

[preprocessor.footnote]
