# SPDX-FileCopyrightText: 2022-2026 TII (SSRC) and the Ghaf contributors
#
# SPDX-License-Identifier: Apache-2.0

name: warn
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  warn-on-workflow-changes:
    # Send a warning and fail this job if any of the listed workflow files are changed.
    # Other workflows continue as normal but the failure will grab author's attention.
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Check if workflow is modified
        id: workflow-changed
        uses: tj-actions/changed-files@e0021407031f5be11a464abee9a0776171c79891 # v47.0.1
        with:
          files: |
            .github/workflows/authorize.yml
            .github/workflows/build.yml
      - name: Send warning
        shell: bash
        run: |
          if [ "${ANY_WORKFLOWS_CHANGED}" == "true" ]; then
            echo "::error::"\
                 "This change edits a workflow file that triggers on 'pull_request_target'. "\
                 "Raising this error to notify that the workflow change will only take "\
                 "impact after merge. "\
                 "Therefore, you need to manually test the change (perhaps in a forked repo) "\
                 "before merging to make sure the change does not break anything." \
                 "Workflow run results, as reported in the github PR actions for this change, "\
                 "will be misleading."
            exit 1
          fi
        env:
          ANY_WORKFLOWS_CHANGED: ${{ steps.workflow-changed.outputs.any_changed }}
